export const all_images=[
  {'src':"./img/av_1.svg", matched: false},
  {'src':"./img/av_2.svg", matched: false},
  {'src':"./img/av_3.svg", matched: false},
  {'src':"./img/av_4.svg", matched: false},
  {'src':"./img/av_5.svg", matched: false},
  {'src':"./img/av_6.svg", matched: false},
  {'src':"./img/av_7.svg", matched: false},
  {'src':"./img/av_8.svg", matched: false},
  {'src':"./img/av_9.svg", matched: false},
  {'src':"./img/av_10.svg", matched: false},
  {'src':"./img/av_11.svg", matched: false},
  {'src':"./img/av_12.svg", matched: false},
  {'src':"./img/av_13.svg", matched: false},
  {'src':"./img/av_14.svg", matched: false},
  {'src':"./img/av_15.svg", matched: false},
]